#!/bin/sh

RUBY_VERSIONS="2.7.8 3.0.6 3.1.4 3.2.2 3.3.0"
ERRORS=""

for VERSION in $RUBY_VERSIONS; do
  eval "$(rbenv init - sh)"
  rbenv shell $VERSION
  printf "testing Ruby $VERSION..."
  if OUTPUT=$(env RUBY="$(rbenv which ruby)" cargo +1.85 test --workspace 2>&1); then
    echo ✅
  else
    ERRORS="$ERRORS\n\n\n$VERSION\n\n$OUTPUT"
    echo ❌
  fi
done
if [ -n "$ERRORS" ]; then
  printf "$ERRORS"
  exit 1
fi
