name: Build Sys

on:
- workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-2019
        ruby-version:
        - "2.6"
        - "2.7"
        - "3.0"
        - "3.1"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Set LD_LIBRARY_PATH
      if: matrix.os == 'ubuntu-latest'
      run: echo LD_LIBRARY_PATH=$(ruby -e 'print RbConfig::CONFIG["libdir"]') >> $GITHUB_ENV
    - name: Fix clang
      if: matrix.os == 'windows-2019' && matrix.ruby-version == '3.1'
      run: |
        pacman --remove --cascade mingw-w64-x86_64-clang
        pacman --sync --noconfirm --needed $ENV:MINGW_PACKAGE_PREFIX-clang
    - name: Build
      shell: bash
      run: build-sys/ruby-${{ matrix.ruby-version }}
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: ruby-sys
        path: ruby-*.rs
